"""creation referentiel section_referentiel question_referentiel appel_offre_referentiel

Revision ID: b5efcff605cf
Revises: e279d028ab56
Create Date: 2026-07-19 17:23:22.126067
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5efcff605cf'
down_revision: Union[str, None] = 'e279d028ab56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referentiel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actif_par_defaut', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_maj', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appel_offre_referentiel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appel_offre_id', sa.UUID(), nullable=False),
    sa.Column('referentiel_id', sa.UUID(), nullable=False),
    sa.Column('date_ajout', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appel_offre_id'], ['appel_offre.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referentiel_id'], ['referentiel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appel_offre_id', 'referentiel_id')
    )
    op.create_table('section_referentiel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referentiel_id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referentiel_id'], ['referentiel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_referentiel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('format_reponse', sa.String(length=50), nullable=False),
    sa.Column('aide_extraction', sa.Text(), nullable=True),
    sa.Column('obligatoire', sa.Boolean(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_maj', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['section_referentiel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_referentiel')
    op.drop_table('section_referentiel')
    op.drop_table('appel_offre_referentiel')
    op.drop_table('referentiel')
    # ### end Alembic commands ###
