"""creation tables appel_offre et document

Revision ID: ca2f1a61f571
Revises: 
Create Date: 2026-07-18 13:23:41.847769
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca2f1a61f571'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appel_offre',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('cree_par', sa.String(length=255), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_maj', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appel_offre_id', sa.UUID(), nullable=False),
    sa.Column('nom_original', sa.String(length=500), nullable=False),
    sa.Column('cle_stockage', sa.String(length=1000), nullable=False),
    sa.Column('fournisseur_stockage', sa.String(length=50), nullable=False),
    sa.Column('type_mime', sa.String(length=255), nullable=False),
    sa.Column('taille_octets', sa.BigInteger(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_maj', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appel_offre_id'], ['appel_offre.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    op.drop_table('appel_offre')
    # ### end Alembic commands ###
