"""allonger nom_original et cle_stockage pour arborescence zip

Revision ID: e279d028ab56
Revises: ca2f1a61f571
Create Date: 2026-07-19 12:10:02.534564
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e279d028ab56'
down_revision: Union[str, None] = 'ca2f1a61f571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'nom_original',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=False)
    op.alter_column('document', 'cle_stockage',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=2500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'cle_stockage',
               existing_type=sa.String(length=2500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    op.alter_column('document', 'nom_original',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
